image: node:lts

pages:
  stage: deploy
  before_script:
    - npm install
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
  script:
    - echo "Build concluído, public pronto para deploy"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
